import type { Metadata } from "next";
import { fontDefault } from "@/src/ui/fonts";
import "@/src/styles/common.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${"light"}`}>
      <body className={`${fontDefault.variable} antialiased`}>{children}</body>
    </html>
  );
}
